/**
 * Conversation PDF Export for Idexal Agents.
 * Export conversations to PDF format with professional styling.
 */

/** Message interface */
export interface PDFMessage {
  id: string
  role: 'user' | 'assistant' | 'system'
  content: string
  timestamp: Date
  attachments?: Array<{
    type: string
    name: string
    url?: string
  }>
}

/** Conversation interface */
export interface PDFConversation {
  id: string
  title: string
  messages: PDFMessage[]
  createdAt: Date
  updatedAt: Date
  participants?: string[]
  tags?: string[]
}

/** PDF export options */
export interface PDFExportOptions {
  /** Include timestamps */
  includeTimestamps: boolean
  /** Include metadata */
  includeMetadata: boolean
  /** Include attachments list */
  includeAttachments: boolean
  /** Page size */
  pageSize: 'a4' | 'letter' | 'legal'
  /** Orientation */
  orientation: 'portrait' | 'landscape'
  /** Margins in mm */
  margins: {
    top: number
    right: number
    bottom: number
    left: number
  }
  /** Custom filename */
  filename: string | undefined
  /** Language for labels */
  language: 'en' | 'ar' | 'zh'
  /** Custom CSS styles */
  customStyles: string | undefined
  /** Include table of contents */
  includeTableOfContents: boolean
  /** Include page numbers */
  includePageNumbers: boolean
  /** Include header */
  includeHeader: boolean
  /** Include footer */
  includeFooter: boolean
}

/** PDF export result */
export interface PDFExportResult {
  /** HTML content ready for PDF generation */
  html: string
  /** Suggested filename */
  filename: string
  /** MIME type */
  mimeType: string
}

/** Default PDF export options */
export const DEFAULT_PDF_OPTIONS: PDFExportOptions = {
  includeTimestamps: true,
  includeMetadata: true,
  includeAttachments: true,
  pageSize: 'a4',
  orientation: 'portrait',
  margins: { top: 20, right: 15, bottom: 20, left: 15 },
  filename: undefined,
  language: 'en',
  customStyles: undefined,
  includeTableOfContents: false,
  includePageNumbers: true,
  includeHeader: true,
  includeFooter: true,
}

/** Labels for PDF export */
const PDF_LABELS: Record<string, Record<string, string>> = {
  en: {
    title: 'Conversation Export',
    date: 'Date',
    participants: 'Participants',
    messages: 'Messages',
    messageCount: 'Total Messages',
    attachments: 'Attachments',
    tags: 'Tags',
    user: 'You',
    assistant: 'Assistant',
    system: 'System',
    tableOfContents: 'Table of Contents',
    page: 'Page',
    generatedBy: 'Generated by Idexal Agents',
    exportedAt: 'Exported at',
  },
  ar: {
    title: 'تصدير المحادثة',
    date: 'التاريخ',
    participants: 'المشاركون',
    messages: 'الرسائل',
    messageCount: 'إجمالي الرسائل',
    attachments: 'المرفقات',
    tags: 'الوسوم',
    user: 'أنت',
    assistant: 'المساعد',
    system: 'النظام',
    tableOfContents: 'جدول المحتويات',
    page: 'صفحة',
    generatedBy: 'تم الإنشاء بواسطة Idexal Agents',
    exportedAt: 'تم التصدير في',
  },
  zh: {
    title: '对话导出',
    date: '日期',
    participants: '参与者',
    messages: '消息',
    messageCount: '总消息数',
    attachments: '附件',
    tags: '标签',
    user: '你',
    assistant: '助手',
    system: '系统',
    tableOfContents: '目录',
    page: '页',
    generatedBy: '由 Idexal Agents 生成',
    exportedAt: '导出时间',
  },
}

/**
 * Generate PDF export for conversation.
 */
export function exportConversationToPDF(
  conversation: PDFConversation,
  options: PDFExportOptions = DEFAULT_PDF_OPTIONS
): PDFExportResult {
  const labels = PDF_LABELS[options.language] ?? PDF_LABELS.en!
  const filename = options.filename ?? `conversation-${conversation.id}.pdf`

  const html = generatePDFHTML(conversation, options, labels)

  return {
    html,
    filename,
    mimeType: 'text/html',
  }
}

/**
 * Generate PDF HTML content.
 */
function generatePDFHTML(
  conversation: PDFConversation,
  options: PDFExportOptions,
  labels: Record<string, string>
): string {
  const styles = generateStyles(options)
  const pageSize = getPageSize(options)

  let html = `<!DOCTYPE html>
<html lang="${options.language}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(conversation.title)}</title>
  <style>
    ${styles}
    ${pageSize}
    ${options.customStyles ?? ''}
  </style>
</head>
<body>
  <div class="container">
    ${options.includeHeader ? generateHeader(conversation, labels) : ''}
    
    ${options.includeMetadata ? generateMetadata(conversation, labels) : ''}
    
    ${options.includeTableOfContents ? generateTOC(conversation, labels) : ''}
    
    <div class="messages-section">
      <h2>${labels.messages}</h2>
      <div class="messages-list">
        ${conversation.messages.map((msg, index) => generateMessage(msg, index, options, labels)).join('\n')}
      </div>
    </div>
    
    ${options.includeFooter ? generateFooter(labels) : ''}
  </div>
  
  ${options.includePageNumbers ? generatePageNumbersScript() : ''}
</body>
</html>`

  return html
}

/**
 * Generate header section.
 */
function generateHeader(
  conversation: PDFConversation,
  labels: Record<string, string>
): string {
  return `
    <header class="header">
      <div class="header-content">
        <h1 class="title">${escapeHtml(conversation.title)}</h1>
        <div class="subtitle">${labels.title}</div>
      </div>
    </header>
  `
}

/**
 * Generate metadata section.
 */
function generateMetadata(
  conversation: PDFConversation,
  labels: Record<string, string>
): string {
  const messageCount = conversation.messages.length
  const attachmentCount = conversation.messages.reduce(
    (sum, msg) => sum + (msg.attachments?.length ?? 0),
    0
  )

  return `
    <div class="metadata">
      <div class="metadata-grid">
        <div class="metadata-item">
          <span class="metadata-label">${labels.date}</span>
          <span class="metadata-value">${formatDate(conversation.createdAt)}</span>
        </div>
        <div class="metadata-item">
          <span class="metadata-label">${labels.messageCount}</span>
          <span class="metadata-value">${messageCount}</span>
        </div>
        ${conversation.participants && conversation.participants.length > 0 ? `
        <div class="metadata-item">
          <span class="metadata-label">${labels.participants}</span>
          <span class="metadata-value">${conversation.participants.join(', ')}</span>
        </div>
        ` : ''}
        ${attachmentCount > 0 ? `
        <div class="metadata-item">
          <span class="metadata-label">${labels.attachments}</span>
          <span class="metadata-value">${attachmentCount}</span>
        </div>
        ` : ''}
        ${conversation.tags && conversation.tags.length > 0 ? `
        <div class="metadata-item">
          <span class="metadata-label">${labels.tags}</span>
          <span class="metadata-value">${conversation.tags.join(', ')}</span>
        </div>
        ` : ''}
      </div>
    </div>
  `
}

/**
 * Generate table of contents.
 */
function generateTOC(
  conversation: PDFConversation,
  labels: Record<string, string>
): string {
  const userMessages = conversation.messages.filter(m => m.role === 'user')
  const assistantMessages = conversation.messages.filter(m => m.role === 'assistant')

  return `
    <div class="toc">
      <h2>${labels.tableOfContents}</h2>
      <ul>
        <li>${labels.user}: ${userMessages.length} ${labels.messages}</li>
        <li>${labels.assistant}: ${assistantMessages.length} ${labels.messages}</li>
      </ul>
    </div>
  `
}

/**
 * Generate a single message.
 */
function generateMessage(
  message: PDFMessage,
  index: number,
  options: PDFExportOptions,
  labels: Record<string, string>
): string {
  const roleLabel = getRoleLabel(message.role, labels)
  const roleClass = `message-${message.role}`

  return `
    <div class="message ${roleClass}" id="msg-${index}">
      <div class="message-header">
        <span class="message-role">${roleLabel}</span>
        ${options.includeTimestamps ? `
        <span class="message-time">${formatDateTime(message.timestamp)}</span>
        ` : ''}
      </div>
      <div class="message-content">
        ${formatMessageContent(message.content)}
      </div>
      ${options.includeAttachments && message.attachments && message.attachments.length > 0 ? `
      <div class="message-attachments">
        ${message.attachments.map(att => `
          <div class="attachment">
            <span class="attachment-icon">📎</span>
            <span class="attachment-name">${escapeHtml(att.name)}</span>
          </div>
        `).join('')}
      </div>
      ` : ''}
    </div>
  `
}

/**
 * Generate footer section.
 */
function generateFooter(labels: Record<string, string>): string {
  return `
    <footer class="footer">
      <div class="footer-content">
        <span>${labels.generatedBy}</span>
        <span>${labels.exportedAt} ${new Date().toLocaleString()}</span>
      </div>
    </footer>
  `
}

/**
 * Generate page numbers script.
 */
function generatePageNumbersScript(): string {
  return `
    <script>
      // Page numbers will be added by the PDF renderer
    </script>
  `
}

/**
 * Generate CSS styles.
 */
function generateStyles(_options: PDFExportOptions): string {
  return `
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      background: #ffffff;
    }

    .container {
      max-width: 100%;
      padding: 20px;
    }

    /* Header */
    .header {
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 20px;
      margin-bottom: 24px;
    }

    .title {
      font-size: 24px;
      font-weight: 700;
      color: #111827;
      margin-bottom: 4px;
    }

    .subtitle {
      font-size: 14px;
      color: #6b7280;
    }

    /* Metadata */
    .metadata {
      background: #f9fafb;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 16px;
      margin-bottom: 24px;
    }

    .metadata-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 16px;
    }

    .metadata-item {
      display: flex;
      flex-direction: column;
    }

    .metadata-label {
      font-size: 12px;
      font-weight: 500;
      color: #6b7280;
      text-transform: uppercase;
      margin-bottom: 4px;
    }

    .metadata-value {
      font-size: 14px;
      color: #111827;
    }

    /* Table of Contents */
    .toc {
      background: #f9fafb;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 16px;
      margin-bottom: 24px;
    }

    .toc h2 {
      font-size: 16px;
      font-weight: 600;
      margin-bottom: 12px;
      color: #111827;
    }

    .toc ul {
      list-style: none;
      padding: 0;
    }

    .toc li {
      font-size: 14px;
      color: #374151;
      padding: 4px 0;
    }

    /* Messages Section */
    .messages-section {
      margin-top: 24px;
    }

    .messages-section h2 {
      font-size: 18px;
      font-weight: 600;
      margin-bottom: 16px;
      color: #111827;
    }

    .messages-list {
      display: flex;
      flex-direction: column;
      gap: 16px;
    }

    /* Message */
    .message {
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 16px;
      page-break-inside: avoid;
    }

    .message-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 8px;
      padding-bottom: 8px;
      border-bottom: 1px solid #f3f4f6;
    }

    .message-role {
      font-weight: 600;
      font-size: 14px;
    }

    .message-time {
      font-size: 12px;
      color: #6b7280;
    }

    .message-content {
      font-size: 14px;
      color: #374151;
      white-space: pre-wrap;
      word-wrap: break-word;
    }

    /* Message Roles */
    .message-user {
      border-left: 3px solid #3b82f6;
      background: #eff6ff;
    }

    .message-user .message-role {
      color: #2563eb;
    }

    .message-assistant {
      border-left: 3px solid #10b981;
      background: #ecfdf5;
    }

    .message-assistant .message-role {
      color: #059669;
    }

    .message-system {
      border-left: 3px solid #f59e0b;
      background: #fffbeb;
    }

    .message-system .message-role {
      color: #d97706;
    }

    /* Attachments */
    .message-attachments {
      margin-top: 12px;
      padding-top: 8px;
      border-top: 1px solid #f3f4f6;
    }

    .attachment {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      background: #f3f4f6;
      padding: 4px 8px;
      border-radius: 4px;
      font-size: 12px;
      margin-right: 8px;
      margin-bottom: 4px;
    }

    .attachment-icon {
      font-size: 12px;
    }

    .attachment-name {
      color: #374151;
    }

    /* Code Blocks */
    .message-content code {
      background: #f3f4f6;
      padding: 2px 6px;
      border-radius: 4px;
      font-family: 'Fira Code', 'Consolas', monospace;
      font-size: 13px;
    }

    .message-content pre {
      background: #1f2937;
      color: #e5e7eb;
      padding: 12px;
      border-radius: 6px;
      overflow-x: auto;
      margin: 8px 0;
    }

    .message-content pre code {
      background: transparent;
      padding: 0;
      color: inherit;
    }

    /* Footer */
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
    }

    .footer-content {
      display: flex;
      justify-content: space-between;
      font-size: 12px;
      color: #9ca3af;
    }

    /* RTL Support */
    [dir="rtl"] .message-user {
      border-left: none;
      border-right: 3px solid #3b82f6;
    }

    [dir="rtl"] .message-assistant {
      border-left: none;
      border-right: 3px solid #10b981;
    }

    [dir="rtl"] .message-system {
      border-left: none;
      border-right: 3px solid #f59e0b;
    }

    /* Print Styles */
    @media print {
      body {
        font-size: 12pt;
      }

      .container {
        padding: 0;
      }

      .message {
        break-inside: avoid;
      }

      .header {
        break-after: avoid;
      }

      .metadata {
        break-inside: avoid;
      }
    }
  `
}

/**
 * Get page size CSS.
 */
function getPageSize(options: PDFExportOptions): string {
  const sizes: Record<string, string> = {
    a4: '@page { size: A4; }',
    letter: '@page { size: letter; }',
    legal: '@page { size: legal; }',
  }

  const margins = options.margins
  const marginCSS = `@page { 
    margin-top: ${margins.top}mm;
    margin-right: ${margins.right}mm;
    margin-bottom: ${margins.bottom}mm;
    margin-left: ${margins.left}mm;
  }`

  return `${sizes[options.pageSize] ?? sizes.a4} ${marginCSS}`
}

/**
 * Format message content with basic markdown.
 */
function formatMessageContent(content: string): string {
  let formatted = escapeHtml(content)

  // Code blocks
  formatted = formatted.replace(/```(\w+)?\n([\s\S]*?)```/g, '<pre><code>$2</code></pre>')

  // Inline code
  formatted = formatted.replace(/`([^`]+)`/g, '<code>$1</code>')

  // Bold
  formatted = formatted.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')

  // Italic
  formatted = formatted.replace(/\*([^*]+)\*/g, '<em>$1</em>')

  // Line breaks
  formatted = formatted.replace(/\n/g, '<br>')

  return formatted
}

/**
 * Get role label.
 */
function getRoleLabel(role: string, labels: Record<string, string>): string {
  switch (role) {
    case 'user':
      return labels.user ?? 'User'
    case 'assistant':
      return labels.assistant ?? 'Assistant'
    case 'system':
      return labels.system ?? 'System'
    default:
      return role
  }
}

/**
 * Format date.
 */
function formatDate(date: Date): string {
  return date.toLocaleDateString()
}

/**
 * Format date and time.
 */
function formatDateTime(date: Date): string {
  return date.toLocaleString()
}

/**
 * Escape HTML special characters.
 */
function escapeHtml(text: string): string {
  const div = document.createElement('div')
  div.textContent = text
  return div.innerHTML
}

/**
 * Download PDF export as HTML file.
 */
export function downloadPDFExport(result: PDFExportResult): void {
  const blob = new Blob([result.html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = result.filename.replace('.pdf', '.html')
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

/**
 * Open PDF in new window for printing.
 */
export function printPDFExport(result: PDFExportResult): void {
  const printWindow = window.open('', '_blank')
  if (printWindow) {
    printWindow.document.write(result.html)
    printWindow.document.close()
    printWindow.print()
  }
}

/**
 * Copy PDF HTML to clipboard.
 */
export async function copyPDFExportToClipboard(result: PDFExportResult): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(result.html)
    return true
  } catch {
    return false
  }
}
