# FUNDING.yml — Support idexla Agents AI Web UI — Free OpenSource Forever
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [idexal, LahbabiCode]
open_collective: #idexal
ko_fi: idexal
custom: ["https://idexal.com", "https://agents.idexal.com", "https://zakariaelahbabi.com"]
